# Generated by Django 3.2.16 on 2022-10-10 15:53

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=120, verbose_name='Activity Name')),
                ('use_personal', models.BooleanField(default=0)),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Activities',
                'verbose_name_plural': 'Activity',
            },
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=120, verbose_name='Activity Category Name')),
                ('image', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('activity', models.ForeignKey(default=1, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='activitiy_categories_relation_activitiy', to='activities.activities')),
            ],
            options={
                'verbose_name': 'ActivityCategories',
                'verbose_name_plural': 'ActivityCategory',
            },
        ),
        migrations.CreateModel(
            name='ActivitySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=120, verbose_name='Activity Sub Category Name')),
                ('status', models.BooleanField(default=1)),
                ('activity', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='ActivitySubCategory_activitiy_name', to='activities.activities')),
                ('activity_category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='activity', chained_model_field='activity', default=1, on_delete=django.db.models.deletion.CASCADE, to='activities.activitycategory')),
            ],
            options={
                'verbose_name': 'ActivitySubCategory',
                'verbose_name_plural': 'ActivitySubCategory',
            },
        ),
    ]
