# Generated by Django 3.2.13 on 2022-06-12 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=None, editable=False, null=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=None, max_length=120, verbose_name='Activity Name')),
                ('status', models.BooleanField(default=1)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Activities',
                'verbose_name_plural': 'Activity',
            },
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=120, verbose_name='Activity Category Name')),
                ('status', models.BooleanField(default=1)),
                ('activity', models.ForeignKey(default=1, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='activitiy_categories_relation_activitiy', to='activities.activities')),
            ],
            options={
                'verbose_name': 'ActivityCategories',
                'verbose_name_plural': 'ActivityCategory',
            },
        ),
    ]
