# Generated by Django 3.2.16 on 2022-10-09 00:07

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=120, verbose_name='Activity Sub Category Name')),
                ('status', models.BooleanField(default=1)),
                ('activity_category', models.ForeignKey(default=1, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='ActivitySubCategory_relation_activitiy_category', to='activities.activitycategory')),
            ],
            options={
                'verbose_name': 'ActivitySubCategory',
                'verbose_name_plural': 'ActivitySubCategory',
            },
        ),
        migrations.CreateModel(
            name='MappingSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_sub_category', models.CharField(blank=None, max_length=120, verbose_name='Mongo Sub Category Name')),
                ('status', models.BooleanField(default=1)),
                ('mapping_activity', models.ForeignKey(default=1, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='MappingSubCategory_relation_activitiy_category', to='activities.activities')),
                ('mapping_activity_category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='mapping_activity', chained_model_field='activity', default=1, on_delete=django.db.models.deletion.CASCADE, to='activities.activitycategory')),
                ('mapping_activity_sub_category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='mapping_activity_category', chained_model_field='activity_category', default=1, on_delete=django.db.models.deletion.CASCADE, to='activities.activitysubcategory')),
            ],
            options={
                'verbose_name': 'MappingSubCategory',
                'verbose_name_plural': 'MappingSubCategory',
            },
        ),
    ]
