# Generated by Django 3.2.13 on 2022-06-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='use_personal',
            field=models.BooleanField(default=0),
        ),
    ]
