# Generated by Django 3.2.13 on 2022-07-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activities_use_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycategory',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
