# Generated by Django 3.2.14 on 2022-07-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=None, editable=False, null=True, verbose_name='Created Date')),
                ('name', models.CharField(blank=None, max_length=120, verbose_name='Demand Name')),
                ('status', models.BooleanField(default=1)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Demands',
                'verbose_name_plural': 'Demand',
            },
        ),
    ]
