# Generated by Django 3.2.16 on 2022-10-10 15:53

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=None, max_length=250, verbose_name='Product Name')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Product Price')),
                ('page_category', models.CharField(blank=None, max_length=250, verbose_name='Page Category Name')),
                ('sub_category', models.CharField(blank=None, max_length=250, verbose_name='Sub Category')),
                ('product_url', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('activity', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_activitiy_name', to='activities.activities')),
                ('activity_category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='activity', chained_model_field='activity', default=1, on_delete=django.db.models.deletion.CASCADE, to='activities.activitycategory')),
                ('activity_sub_category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='activity_category', chained_model_field='activity_category', default=1, on_delete=django.db.models.deletion.CASCADE, to='activities.activitysubcategory')),
                ('company', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='prodcut_company_name', to='companies.companies')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_product_activity_category_id', models.IntegerField(null=None, verbose_name='first_product_activity_category_id')),
                ('first_company_id', models.IntegerField(null=None, verbose_name='first_company_id')),
                ('first_product_id', models.IntegerField(null=None, verbose_name='first_product_id')),
                ('first_product_name', models.CharField(blank=None, max_length=250, verbose_name='first_product_name')),
                ('second_product_activity_category_id', models.IntegerField(null=None, verbose_name='second_product_activity_category_id')),
                ('second_company_id', models.IntegerField(null=None, verbose_name='second_company_id')),
                ('second_product_id', models.IntegerField(null=None, verbose_name='first_product_id')),
                ('second_product_name', models.CharField(blank=None, max_length=250, verbose_name='second_product_name')),
                ('matched_score', models.FloatField(null=None, verbose_name='Matched Score')),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('matches_activity', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='ProductMatches_matches_activity', to='activities.activities')),
            ],
            options={
                'verbose_name': 'ProductMatches',
                'verbose_name_plural': 'ProductMatched',
            },
        ),
    ]
