# Generated by Django 3.2.13 on 2022-06-12 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=None, editable=False, null=True, verbose_name='Created Date')),
                ('product_name', models.CharField(blank=None, max_length=250, verbose_name='Product Name')),
                ('page_category', models.CharField(blank=None, max_length=250, verbose_name='Page Category Name')),
                ('sub_category', models.CharField(blank=None, max_length=250, verbose_name='Sub Category')),
                ('image', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated Date')),
                ('activity', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_activitiy_name', to='activities.activities')),
                ('activity_category', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_main_category_name', to='activities.activitycategory')),
                ('company', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='prodcut_company_name', to='companies.companies')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=None, editable=False, null=True, verbose_name='Created Date')),
                ('first_product_activity_category_id', models.IntegerField(null=None, verbose_name='first_product_activity_category_id')),
                ('first_company_id', models.IntegerField(null=None, verbose_name='first_company_id')),
                ('first_product_id', models.IntegerField(null=None, verbose_name='first_product_id')),
                ('first_product_name', models.CharField(blank=None, max_length=250, verbose_name='first_product_name')),
                ('second_product_activity_category_id', models.IntegerField(null=None, verbose_name='second_product_activity_category_id')),
                ('second_company_id', models.IntegerField(null=None, verbose_name='second_company_id')),
                ('second_product_id', models.IntegerField(null=None, verbose_name='first_product_id')),
                ('second_product_name', models.CharField(blank=None, max_length=250, verbose_name='second_product_name')),
                ('matched_score', models.FloatField(null=None, verbose_name='Matched Score')),
                ('status', models.BooleanField(default=1)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated Date')),
                ('matches_activity', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='ProductMatches_matches_activity', to='activities.activities')),
            ],
            options={
                'verbose_name': 'ProductMatches',
                'verbose_name_plural': 'ProductMatched',
            },
        ),
    ]
