# Generated by Django 3.2.13 on 2022-07-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Product Price'),
        ),
    ]
