# Generated by Django 3.2.16 on 2022-10-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmatches',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='productmatches',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date'),
        ),
    ]
