# Generated by Django 3.2.13 on 2022-07-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Product Price'),
        ),
    ]
