# Generated by Django 3.2.13 on 2022-07-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
