# Generated by Django 3.2.13 on 2022-06-12 10:08

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('demands', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawlers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=None, editable=False, null=True, verbose_name='Created Date')),
                ('page_url', models.CharField(blank=None, max_length=120, verbose_name='Page Url')),
                ('page_numbers', models.IntegerField(blank=True, default=0, null=True, verbose_name='Page Numbers')),
                ('page_name', models.CharField(blank=None, max_length=120, verbose_name='Page Name')),
                ('page_category', models.CharField(blank=True, max_length=120, null=True, verbose_name='Page Category')),
                ('css_selector', models.CharField(blank=True, max_length=120, null=True, verbose_name='Css Selector')),
                ('schedule', models.CharField(blank=True, max_length=120, null=True, verbose_name='Schedule Config')),
                ('status', models.BooleanField(default=1)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated Date')),
                ('activity', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='activitiy_name', to='activities.activities')),
                ('activity_category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='activity', chained_model_field='activity', on_delete=django.db.models.deletion.CASCADE, to='activities.activitycategory')),
                ('company', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='companies.companies')),
                ('demand', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='demands_name', to='demands.demands')),
            ],
            options={
                'verbose_name': 'Crawlers',
                'verbose_name_plural': 'Crawler',
            },
        ),
    ]
