# Generated by Django 3.2.13 on 2022-05-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlers',
            name='css_selector',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Css Selector'),
        ),
    ]
