# Generated by Django 3.2.15 on 2022-09-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDriverConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=120, null=True, verbose_name='IP address')),
            ],
            options={
                'verbose_name': 'WebDriver',
                'verbose_name_plural': 'WebDriver',
            },
        ),
        migrations.AlterModelOptions(
            name='crawlersconfig',
            options={'verbose_name': 'Crawler Config', 'verbose_name_plural': 'Crawler Config'},
        ),
    ]
