# Generated by Django 3.2.13 on 2022-06-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlers',
            name='page_url',
            field=models.CharField(blank=None, max_length=255, verbose_name='Page Url'),
        ),
    ]
