# Generated by Django 3.2.13 on 2022-07-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activitycategory_image'),
        ('demands', '0001_initial'),
        ('companies', '0002_companies_page_name'),
        ('crawlers', '0002_alter_crawlers_page_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawler_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='Crawler ID')),
                ('error_message', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Crawler Err',
                'verbose_name_plural': 'Crawler Err',
            },
        ),
        migrations.AlterField(
            model_name='crawlers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='crawlers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update Date'),
        ),
        migrations.CreateModel(
            name='CrawlersConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_selector', models.CharField(blank=True, max_length=120, null=True, verbose_name='Css Selector')),
                ('p1', models.CharField(blank=True, max_length=120, null=True, verbose_name='p1')),
                ('p2', models.CharField(blank=True, max_length=120, null=True, verbose_name='p2')),
                ('p3', models.CharField(blank=True, max_length=120, null=True, verbose_name='p3')),
                ('p4', models.CharField(blank=True, max_length=120, null=True, verbose_name='p4')),
                ('p5', models.CharField(blank=True, max_length=120, null=True, verbose_name='p5')),
                ('p6', models.CharField(blank=True, max_length=120, null=True, verbose_name='p6')),
                ('p7', models.CharField(blank=True, max_length=120, null=True, verbose_name='p7')),
                ('p8', models.CharField(blank=True, max_length=120, null=True, verbose_name='p8')),
                ('p9', models.CharField(blank=True, max_length=120, null=True, verbose_name='p9')),
                ('p10', models.CharField(blank=True, max_length=120, null=True, verbose_name='p10')),
                ('p11', models.CharField(blank=True, max_length=120, null=True, verbose_name='p11')),
                ('p12', models.CharField(blank=True, max_length=120, null=True, verbose_name='p12')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('activity', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='crawler_config_activitiy_name', to='activities.activities')),
                ('company', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='crawler_config_company_name', to='companies.companies')),
                ('demand', models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, related_name='crawler_config_demands_name', to='demands.demands')),
            ],
            options={
                'verbose_name': 'Crawler Config',
                'verbose_name_plural': 'Crawler Congig',
            },
        ),
    ]
