# Generated by Django 3.2.13 on 2022-05-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0002_crawlers_css_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlers',
            name='page_numbers',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Page Numbers'),
        ),
    ]
