# Generated by Django 3.2.15 on 2022-09-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0002_auto_20220905_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlersconfig',
            name='p13',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='p13'),
        ),
        migrations.AddField(
            model_name='crawlersconfig',
            name='p14',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='p14'),
        ),
        migrations.AddField(
            model_name='crawlersconfig',
            name='p15',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='p15'),
        ),
        migrations.AddField(
            model_name='crawlersconfig',
            name='p16',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='p16'),
        ),
        migrations.AddField(
            model_name='crawlersconfig',
            name='p17',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='p17'),
        ),
        migrations.AddField(
            model_name='crawlersconfig',
            name='p18',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='p18'),
        ),
        migrations.AddField(
            model_name='crawlersconfig',
            name='p19',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='p19'),
        ),
        migrations.AddField(
            model_name='crawlersconfig',
            name='p20',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='p20'),
        ),
    ]
