# Generated by Django 3.2.13 on 2022-05-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0003_crawlers_page_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlers',
            name='categor',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='crawlers',
            name='page_numbers',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Page Numbers'),
        ),
    ]
