# Generated by Django 3.2.13 on 2022-05-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0004_auto_20220507_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlers',
            old_name='categor',
            new_name='category',
        ),
    ]
