# Generated by Django 3.2.14 on 2022-07-30 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.SlugField(blank=True, null=True, verbose_name='Profile')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('is_online', models.BooleanField(default=0, verbose_name='Online ?')),
                ('form_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Form Company')),
                ('verified', models.BooleanField(default=0, verbose_name=' Hesap Doğrulandı')),
                ('verified_code', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Account',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Type')),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Type',
            },
        ),
        migrations.CreateModel(
            name='PersonalUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_user_activity_activity', to='activities.activities')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_user_activity_user', to='account.account')),
            ],
            options={
                'verbose_name': 'Personal User Activity',
                'verbose_name_plural': 'Personal User Activity',
            },
        ),
        migrations.CreateModel(
            name='AccountCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_company_activity', to='activities.activities')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_company_company', to='companies.companies')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_company_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Company Relations',
                'verbose_name_plural': 'Account Company Relations',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_user_type', to='account.usertype'),
        ),
    ]
