# Generated by Django 3.2.13 on 2022-05-02 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.SlugField(blank=True, null=True, verbose_name='Profil Adresi')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası')),
                ('is_online', models.BooleanField(default=0, verbose_name='Online ?')),
                ('user_type', models.IntegerField(choices=[(1, 'Admin'), (2, 'Company'), (3, 'Operation')], verbose_name='Kullanıcı Tipi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hesap',
                'verbose_name_plural': 'Kullanıcı Hesapları',
            },
        ),
    ]
