# Generated by Django 3.2.13 on 2022-06-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name': 'User Type', 'verbose_name_plural': 'User Type'},
        ),
    ]
