# Generated by Django 3.2.13 on 2022-06-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_form_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verified',
            field=models.BooleanField(default=0, verbose_name=' Hesap Doğrulandı'),
        ),
        migrations.AddField(
            model_name='account',
            name='verified_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
