# Generated by Django 3.2.13 on 2022-06-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('account', '0004_auto_20220618_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_user_activity_activity', to='activities.activities')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_user_activity_user', to='account.account')),
            ],
        ),
    ]
