# Generated by Django 3.2.13 on 2022-06-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_personaluseractivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaluseractivity',
            options={'verbose_name': 'Personal User Activity', 'verbose_name_plural': 'Personal User Activity'},
        ),
    ]
